version: '3.9'

services:
  evidently_app:
    build: 
      context: dashboards
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - FLASK_APP=evidently_app.py
    volumes:
      - ./dashboards:/app

  streamlit_app:
    build:
      context: streamlit
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - STREAMLIT_SERVER_PORT=80
    volumes:
      - ./models:/models
      - ./streamlit:/app